version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: myrootpw
      MYSQL_DATABASE: my_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    command: npm run start:dev
    ports:
      - '5000:5000'
    env_file:
      - ./env/backend.env
    depends_on:
      - 'mysql'
    volumes:
      - ./backend:/app
      - /app/node_modules


  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - keycloak
      
  keycloak:
    container_name: keycloak
    build: 
      context: ./keycloak
      dockerfile: keycloak.dockerfile
    ports:
      - '4000:8080'
    env_file:
      - ./env/keycloak.env
      
volumes:
  mysql_data:
      driver: local